micronaut:
  application:
    name: kotlinaut
    
##datasources:
##  default:
##   url: jdbc:mysql://localhost:3307/testando
##   username: root
##  password: root
##  dialect: MYSQL
##  validation-query: "SELECT 1"
##  connection-test-query: "SELECT 1"

jpa:
  default:
    entity-scan:
      packages: 'com.teste.infra.persistence.mysql.entity'
    properties:
      hibernate:
        physical_naming_strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
        hbm2ddl:
          auto: validate
        show_sql: true